### ISSUE TITLE
Change database from mongodb to postgresql

### ISSUE THREAD

**Issue by qouv** [swe574-Fall2024-Group1/huddleup#12]
We should change the database.

**Comment by dorukbu** [comment]
I'll add the postgresql container to docker-compose file after this task, so that everyone can spin up the app and the required database instance with just one `docker compose up` command locally.

**Comment by aaldaber** [comment]
Made the needed modifications, and also added the container to docker compose file. Will be solved after merging https://github.com/swe574-Fall2024-Group1/huddleup/pull/16
