### ISSUE TITLE
Shall moderators or owners be able to manually give a "community specific badge" to a member?

### ISSUE THREAD

**Issue by ovuncertunc** [swe574-Fall2024-Group1/huddleup#20]
Whether community specific badges can be manually given to members

**Comment by qouv** [comment]
**_Customer comments_**

Yes they should.

**Comment by qouv** [comment]
Here is an idea: 

We should have 3 types of badges which are manuals, top lists(like top liked, top post shared) and numerical badges ( like having over 300 posts). @ovuncertunc

**Comment by ovuncertunc** [comment]
The question is asked to the instructor and discussed inside us. There will be manual badges with a specific name and description.
