### ISSUE TITLE
Decide on branching strategy

### ISSUE THREAD

**Issue by dorukbu** [swe574-Fall2024-Group1/huddleup#4]

**Comment by aaldaber** [comment]
We can do functionality name == branch name, and when the functionality is completed a Merge request is sent to the main branch

**Comment by dorukbu** [comment]
There can also be a dev branch which will be deployed to test environment.
So the branching strategy is as follows:
- **test** branch which will accept merges from feature branches and will be deployed to test environment automatically upon merge.
- **main** branch will allow merges only from dev branch and there will be an automatic deployment to the prod env. following merge.
- feature, bug etc. branches to facilitate development

**Comment by ovuncertunc** [comment]
I think feature branch --> dev branch --> main branch is simpler. In the dev branch we can deploy to the test environment
