### ISSUE TITLE
Determine Post-Tag Entity Relation

### ISSUE THREAD

**Issue by ustaoglumuharrem** [swe574-Fall2024-Group1/huddleup#46]

**Comment by ustaoglumuharrem** [comment]
Post -Tag relation have Many to Many

Models
Post model updated to have many-to-many relation with Tag
class Post(models.Model):
    createdBy = models.ForeignKey('authAPI.User', on_delete=models.CASCADE)
    community = models.ForeignKey('Community', on_delete=models.CASCADE)
    template = models.ForeignKey('Template', on_delete=models.CASCADE)
    rowValues = models.JSONField(default=list)
    createdAt = models.DateTimeField(auto_now_add=True)
    isEdited = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name='posts')  ->Tags can be added to posts

class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    description = models.CharField(max_length=200, blank=True)  # Add description field
    createdBy = models.ForeignKey('authAPI.User', on_delete=models.CASCADE)
    createdAt = models.DateTimeField(auto_now_add=True)

**Comment by aaldaber** [comment]
When registering or when going to own profile, a user can select several tags that are of interest to him.

After that, we can recommend the users relevant communities, or users based on

tag similarity - for first version
social score - a count of users that a user is following that follow the same communities

**Comment by aaldaber** [comment]
@ustaoglumuharrem for the Post-Tag relationship I went with a django-taggit package. The package is easy to use and provides all the necessary functionality that we might need. You can take a look at the code at feature/adding_tags_to_posts branch.
