### ISSUE TITLE
Create CI pipeline for unit tests

### ISSUE THREAD

**Issue by dorukbu** [swe574-Fall2024-Group1/huddleup#58]
1. Set up a GitHub Actions workflow to run unit tests on each merge request to the development branch.
2. Configure the workflow to trigger automatically on pull request events.
3. Set up branch protection rules for the development branch to require a successful run of the unit test workflow.

**Comment by aaldaber** [comment]
@dorukbu the command to run tests is `python manage.py test`

**Comment by dorukbu** [comment]
I made the required changes and crated a PR.
Please see the details under [PR comments](https://github.com/swe574-Fall2024-Group1/huddleup/pull/63).
